version: "3.7"
services:
  mysql:
    container_name: mysqlserver
    image: mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=EI_ANALYTICS
    expose:
      - 3306

  server:
    image: wso2/ei-analytics-server:latest
    environment:
      mysql_server_name: mysqlserver
      mysql_port: 3306
      mysql_databasename: EI_ANALYTICS
      mysql_username: root
      mysql_password: root
    depends_on:
      - mysql
    expose:
      - 7712
      - 7612
    ports:
      - 7712:7712
      - 7612:7612

  portal:
    image: wso2/ei-analytics-portal:latest
    environment:
      mysql_server_name: mysqlserver
      mysql_port: 3306
      mysql_databasename: EI_ANALYTICS
      mysql_username: root
      mysql_password: root
    depends_on:
      - mysql
    expose:
      - 9645
    ports:
      - 9645:9645
